services:
    mongo:
        container_name: mongo-container
        image: mongo
        restart: always
        ports:
          - "27017:27017"
    api:
        container_name: api-container
        build: .
        environment:
            - MONGO_URL=mongodb://mongo:27017/favorite-product-service
        volumes:
            - ./dist:/usr/src/app/dist
        ports:
            - "${PORT}:3000"
        links:
            - mongo