services:
    mongo:
        container_name: mongo-container
        image: mongo
        restart: always
        ports:
          - "27017:27017"
    swagger:
        container_name: doc-container
        image: swaggerapi/swagger-ui
        ports:
            - "${SWAGGER_UI_PORT}:8080"
        environment:
            - BASE_URL=/
            - SWAGGER_JSON=/spec/openapi.yml
        volumes:
            - ./src/doc:/spec
    api:
        container_name: api-container
        build: .
        environment:
            - MONGO_URL=mongodb://mongo:27017/favorite-product-service
        ports:
            - "${PORT}:3000"
        links:
            - mongo